services:
  rag-ingestion-admin:
    image: rag-ingestion-admin:latest
    build: .
    container_name: rag-ingestion-admin
    env_file:
      - .env
    environment:
      VECTOR_STORE_ID: '${VECTOR_STORE_ID:-2}'
      ADMIN_API_PORT: '${ADMIN_API_PORT:-8094}'
      UPLOAD_DIR: /app/uploads
      FILE_REGISTRY_PATH: /app/file_registry/files.json
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./file_registry:/app/file_registry
      - ./output_files:/app/output_files
      - ./testfiles:/app/testfiles
    command: uvicorn admin_api:app --host 0.0.0.0 --port 8094
    ports:
      - "8094:8094"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
